### ISSUE TITLE
Integrate spatial memory games within the test system

### ISSUE THREAD

**Issue by DamonGreenhalgh** [uoa-compsci399-s2-2022/spatial-skills-web-app#25]
## Feature Description
Integrate the pattern and card matching games within the testing framework.

## User Story
"As a user I would like to be tested on all visuospatial skills within a single test"

## MVP
Be able to identify if a memory game is used in the test and integrate it within the test. If possible allow them to be played in any order, i.e. static, static, memory, static, etc.

**Comment by wukelang** [comment]
## Progress
Integrated memory games into the test system by creating question objects in MongoDB that represent the memory games.
![image](https://user-images.githubusercontent.com/29995754/190412509-e9c7ae96-8cb7-4138-b1a2-e53da43a2d6f.png)
These questions can be added to a test object in the DB. 

The `Test` component checks if the current question category is "Memory", before checking if the title is either "MatchingGame" or "PatternGame". If it meets these conditions, then the respective memory game is loaded into the test page.
- The time given to complete these memory games is parsed from the time value in the test object (from DB).
- I've changed the `studentanswer` object to include a 'value' field, since memory / text games won't have answers like multichoice questions do.
- The memory games are treated as regular questions, so they can be fitted in any order within the test.

##  Things to work on
Mostly backend stuff.
- Change answer marking endpoints to check if the question is a memory question, then using its value field. 
  - Handle null aId's (they didn't select an answer for multichoice).
  - Include more information for each question on the `answer/getStudentAnswer` endpoint
- `test/getquestions` endpoint retrieves questions in order of their creation date (?). Fix this so question order is the same as the array given.

CSS for memory games could also be improved, although its not major. Green start button should be changed.

## Other stuff
I hid the footer on the test page since it didn't seem practical to have it there.

**Comment by wukelang** [comment]
### Progress
Improved our backend endpoints. 
- Backend can now mark memory / entry questions and questions with no answer submitted
- Test questions now retrieved in its given order in the test object
- More information shown on the `answer/getStudentAnswer` endpoint
![image](https://user-images.githubusercontent.com/29995754/191256116-1fc4d892-c100-4ffc-a019-de69e8902ddb.png)
- Multichoice questions can have their answer order randomised

Results page is broken but we weren't going to use it anyway. I think my work on this branch is finished.
